### ISSUE TITLE
Should `with` even be a part of this proposal?

### ISSUE THREAD

**Issue by TehShrike** [rricard/proposal-const-value-types#41] opened 2019-08-16 22:43 UTC
Continuing a thread from #1 – is there a compelling reason to include `with` in this proposal?

I don't believe this proposal needs the `with` syntax to be viable. I also doubt that the proposed `with` syntax needs to be specific to immutable data structures – `someObject with .b=5` would be handy as sugar for `Object.assign({}, someObject, { b: 5 })`.

Context:
- https://github.com/rricard/proposal-const-value-types/issues/1#issuecomment-502725556
- https://github.com/rricard/proposal-const-value-types/issues/1#issuecomment-521263307
- https://github.com/rricard/proposal-const-value-types/issues/37#issuecomment-522159428

**Comment by ceigey** [comment] 2019-08-17 06:01
I feel like having the two together is a good idea; otherwise, you might end up with a situation where, despite immutable data structures existing in the runtime, people are using good ol fashioned pretend-immutable data structures with libraries like Immer for the better developer ergonomics when making deep changes instead.

But, I do also feel like having something akin to Immer built in to JS is a great idea on its own too, and this repurposing of the `with` keyword provides that.

Speaking of deep property access, another question is what happens to `?.` and when the path the mutation is being made at doesn't exist; could `?.` be used to automatically fill in said path? And if so, do we assume that tuples are secretly a subset of records and records can be made from tuples?

So... if the proposal was split up, I wonder how deep their shared concerns would be; but evidently there's already other proposals that are completely separate that would have to be considered too.

**Comment by TehShrike** [comment] 2019-08-17 16:32
[zenflow](https://github.com/rricard/proposal-const-value-types/issues/1#issuecomment-499595272) brought up that the spread syntax already exists and would accomplish the same thing without adding a new language feature.

**Comment by ceigey** [comment] 2019-08-17 17:06
Spread syntax is ergonomic at one level deep, but after that, while perfectly functional, the syntax is not ideal and requires a fair bit of repetition.

Consider:

```javascript
let myRec = #{
  user: {
    address: {
      street: 'First St',
      //...
    }
    //...
  }
  //...
}

let newRecord = #{
  ...myRec,
  user: {
    ...myRec.user,
    address: {
      ...myRec.user.address,
      street: 'Second Ave'
    }
  }
}
```

The update would be better as something like:
```javascript
myRec.user.address.street = 'Second Ave';
```
... but that won't fly because we're dealing with immutable objects and the assignment operator can't "return" a value to assign to something else.

Without a better way to update deeply nested properties in a record, I'd rather stick to immer and mutable objects for those use cases, or avoid nested records and tuples entirely.

**Comment by ljharb** [comment] 2019-08-17 17:11
then rather than with, I’d prefer to see + used for that use case (and ideally - as well, if possible)

**Comment by ceigey** [comment] 2019-08-17 17:29
As in
```javascript
let newRec = #{ x: { val: 2 }, y: 5 } + #{ x: { val: 0 } };
newRec === #{ x: { val: 0 }, y: 5 };
```

... or ....
```javascript
let newRec = #{ x: { val: 2 } } + .x.val = 0
```
?

(I'm assuming `let newRec = rec.x.val + 0` would be too ambiguous and confusing)

**Comment by ljharb** [comment] 2019-08-17 18:07
The former, and yes, ideally the operator would throw if you tried to combine an immutable type with a non-immutable one.

**Comment by isiahmeadows** [comment] 2019-08-17 20:01
Related: #19

**Comment by ceigey** [comment] 2019-08-18 02:28
@ljharb hmm interesting, I like it. It reinforces that there's certain special properties to these data structures too, and gets rid of the need for additional syntax for deep updates.

Main concern is whether overloading `+` and adding a throwing behaviour* would cause less confusion than adding a whole new syntax feature.

*(then again... are silent failures caused by strings + numbers really that enviable? Though that'd mean you'd have to stringify your records before string concatenation *or* interpolate them)

Using the user.street.address example:
```javascript

let newRec = myRec + #{ user: { street: { address: 'Foo Blvd' }}}
```

... a little more verbose but yeah that works well. Plus you also create the path if it doesn't already exist.

**Comment by ljharb** [comment] 2019-08-18 04:31
Symbols already require explicit stringification, so there’s precedent there.

**Comment by Alexsey** [comment] 2019-08-18 11:02
@ljharb why do you think that combination of mutable and immutable data structures is a bad idea? It should not be a problem to convert a mutable object to immutable analog, and in cases when it would be required developers will do it - there is no second scenario to follow

```
```

About `someObject with .b = 5` syntax - maybe dot in construction `<operator> .b` should also become a separate syntax (proposal) beyond `with` use case? For example, I would be happy to do
```
const names = users.map(user => .name)
// or
const  trimmedLines = lines.map(line => .trim())
```
and there is a demand on such shorthands - for example `lodash` provides for this
```
const names = users.map('name')
// and
const trimmedLines = lines.invokeMap('trim')
```
but this alternatives uses string literals an thought are error prone

```
```

If we are talking about the operator that in some codebases would be used instead of `=` which means REALLY often - maybe it should be shorter than 4 symbols?

**Comment by ljharb** [comment] 2019-08-18 14:54
Implicit coercion is something worth avoiding, even if it’s easy.

Separately, one shouldn’t optimize for writing, but for reading - since the latter happens way more often than the former.

**Comment by mheiber** [comment] 2019-08-28 16:26
For what it's worth, my own personal opinion is that it would be good to see a PR for removing 'with' from the current proposal, with the idea that it would make sense as a follow-on.

`with` has value, in my opinion, but ideally wouldn't impede progress in achieving the core goals of the proposal.

**Comment by rricard** [comment] 2019-09-10 13:30
See #49, we intend to merge this sometimes this week

**Comment by rricard** [comment] 2019-09-10 14:46
`with` has been removed from the current proposal

**Closed by rricard** 2019-09-10 14:46 UTC

**Comment by Jack-Works** [comment] 2020-03-06 02:41
Then what about a immer.js like API?

```js
Record.with(#{xyz: 1}, x => {
    x.xyz = 2
}) // return #{xyz: 2}
```

**Comment by rickbutton** [comment] 2020-03-06 02:44
@Jack-Works I think [`Record.assign()` in the namespace/prototype appendix](https://github.com/tc39/proposal-record-tuple/blob/master/NS-Proto-Appendix.md#recordassignargs-record---record) fulfills that use case nicely:

```js
Record.assign(#{ xyz: 1 }, #{ xyz: 2 }) === #{ xyz: 1 }
```

**Comment by Jack-Works** [comment] 2020-03-06 02:47
> @Jack-Works I think [`Record.assign()` in the namespace/prototype appendix](https://github.com/tc39/proposal-record-tuple/blob/master/NS-Proto-Appendix.md#recordassignargs-record---record) fulfills that use case nicely:
> 
> ```js
> Record.assign(#{ xyz: 1 }, #{ xyz: 2 }) === #{ xyz: 1 }
> ```

Does it assign the record deeply? Does it also work for tuple?

```js
Record.assign(#{ xyz: #{abc: 1} }, #{ xyz: #{cde: 2} }) === #{ xyz: ??? }
```

**Comment by rickbutton** [comment] 2020-03-06 04:07
hmm, good question! As specified `Record.assign` is a shallow operation like `Object.assign`, but I think it would be feasible to describe a deeper version, ignoring unknown unknowns. Bikeshedding: `Record.deepAssign`?

**Comment by Jack-Works** [comment] 2020-03-06 08:21
Deep assign might be a footgun imo

It will be better to have a immer js like API . A Proxy like object is passed in, developer can modify it like an ordinary object, then after the modify, the proxy is revoked.
